# Generated by Django 6.0.3 on 2026-03-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=50)),
                ('patient_id', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('gender', models.CharField(max_length=10)),
                ('birth_date', models.DateField()),
                ('name', models.JSONField()),
                ('identifier', models.JSONField()),
                ('telecom', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
